### ISSUE TITLE
Set supported python version to >=3.9 - 577

### ISSUE THREAD

**Issue by redhat-qe-bot1** [RedHatQE/ocp-addons-operators-cli#578]
[Auto generated]
Number: [#577]

**Comment by redhat-qe-bot2** [comment]
[38;5;184mocp-addons-operators-cli[0m[pull_request][9b72-11ef-9d06-7d0956a69dc0][PR 577]: Closing issue for PR: Set supported python version to >=3.9.
PR was closed.
